{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "236dd964_519fd478",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000004
      },
      "writtenOn": "2022-03-07T22:06:29Z",
      "side": 1,
      "message": "We\u0027ve been moving over to pldm for all new systems so I don\u0027t see any issues with this no longer generating an error.",
      "revId": "07bcc00c6c328171342f37c74bd9ba3e626a13d4",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "6be99d7f_cc6abcbd",
        "filename": "host-cmd-manager.cpp",
        "patchSetId": 1
      },
      "lineNbr": 142,
      "author": {
        "id": 1000163
      },
      "writtenOn": "2022-03-07T23:50:05Z",
      "side": 1,
      "message": "I know this isn\u0027t the part that changed, but I don\u0027t think bus.call() ever returns without an exception but still setting reply.is_method_error() as true.\n\nThat is to say the only place the try-catch needs to be is around the call() function (and then remove the elog because that throws too).",
      "range": {
        "startLine": 138,
        "startChar": 11,
        "endLine": 142,
        "endChar": 13
      },
      "revId": "07bcc00c6c328171342f37c74bd9ba3e626a13d4",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}